name: "CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: 'Enable corepack'
        run: corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'yarn'

      - name: "Install dependencies"
        run: yarn install --immutable

      - name: "Lint"
        run: yarn lint -f @ver0/gha

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: 'Enable corepack'
        run: corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'yarn'

      - name: "Install dependencies"
        run: yarn install --immutable

      - name: "Build"
        run: yarn build

  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: 'Enable corepack'
        run: corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'yarn'

      - name: "Install dependencies"
        run: yarn install --immutable

      - name: "Test"
        run: yarn test:coverage --reporter='github-actions' --reporter='junit' --outputFile='./coverage/test-report.junit.xml' --reporter=default

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/test-report.junit.xml
          fail_ci_if_error: true

      - name: "Upload test results to Codecov"
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/test-report.junit.xml
          fail_ci_if_error: true

  dependabot-merge:
    name: "Dependabot automerge"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    needs: [ "test", "build", "lint" ]
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  semantic-release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: [ "test", "build", "lint" ]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    outputs:
      new-release-published: ${{ steps.release.outputs.new-release-published }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          ref: "master"
      - name: 'Enable corepack'
        run: corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: "Build"
        run: yarn build

      - name: "Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
